# .streamlit/secrets.toml

[reddit]
client_id = "L5x_OBLY_HG9UxgxfOg69Q"
client_secret = "3f2igWO4Hdcu404B3KxVV81nE_hnsA"
user_agent = "python:StockPredictionApp:v1.0 (by /u/Stock_prediction)"
username = "Stock_prediction"
password = "curry666666"

# .streamlit/secrets.toml
[mongo]
uri = "mongodb+srv://zhongjiayou1204:Zjy2022%4000@trendsage.svfhdvw.mongodb.net/?retryWrites=true&w=majority&tlsCAFile=isrgrootx1.pem"

db_name = "stock_trends"
collection_name = "trending_stocks"
